# -*- coding: utf-8 -*-
"""pro130

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qlXvr8eGd2Wjq12E9jWmJy9ohffkMRmQ
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import csv

df=pd.read_csv('total_stars.csv')
df

df.columns

df.drop(['Unnamed: 0','Unnamed: 6','Star_name.1','Distance.1','Mass.1','Radius.1','Luminosity'],axis=1,inplace=True)

df

final_data=df.dropna()
final_data

final_data.reset_index(drop=True,inplace=True)
final_data

final_data.to_csv('final_data.csv')

final_data.info()

final_data.describe()

final_data.head(5)

final_data.dtypes